### ISSUE TITLE
should we delete this repo? 

### ISSUE THREAD

**Issue by lassediercks** [Jimdo/Template-Standup-Music#3]
:cry:  

ptal @nesQuick @Jimdo/background-area-taskforce

**Comment by nesQuick** [comment]
I'd suggest to keep it for two reasons:

1. It's kind of documentation, for the dashboard which still references to the repo
2. It's "open source" so doesn't count to the amount of private repos we have

**Comment by lassediercks** [comment]
ok

**Comment by Xiphe** [comment]
nostalgic template team flashback incoming

**Comment by HerrBertling** [comment]
Awwwwww 😍

**Comment by bastiank** [comment]
wait for it !! 💋
